class Plugin:
    def set_solver(self):
        ...

    def on_start(self):
        ...

    def on_phase_finish(self):
        ...

    def on_finish(self):
        ...

    def on_new_points_to_set(self, cs_var, pts):
        ...

    def on_new_call_edge(self, edge):
        ...

    def on_new_method(self, method):
        ...

    def on_new_stmt(self, stmt, method):
        ...

    def on_new_cs_method(self, cs_method):
        ...

    def on_unresolved_call(self, recv, context, invoke):
        ...